name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: 'npm'

      - name: npm install and npm run build
        env:
          WS_ENDPOINT: ${{ secrets.WS_ENDPOINT }}
        run: |
          npm ci
          npm run build
          mv dist/Executioner-frontend/index.html dist/Executioner-frontend/index.htm
          cat dist/Executioner-frontend/index.htm > dist/Executioner-frontend/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/Executioner-frontend # The folder the action should deploy.
